name: Python test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    - name: Start services
      run: docker-compose up --build -d

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if echo 'SELECT 1' | mysql -h 127.0.0.1 -uroot -proot-pass test &> /dev/null; then
            break
          fi
          echo "Waiting for MySQL..."
          sleep 1
        done

    - name: Wait for Neo4j to be ready
      run: |
        for i in {1..30}; do
          if curl -sS -o /dev/null -w "%{http_code}" http://localhost:7474 | grep -q 200; then
            break
          fi
          echo "Waiting for Neo4j..."
          sleep 1
        done

    - name: Run tests
      run: |
        pytest --cov=traits --cov-report=xml --cov-report=html

    - name: Shut down services
      run: docker-compose down
